M48
; DRILL file {KiCad 9.0.2} date 2025-06-28T16:23:12+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-28T16:23:12+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.150
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
%
G90
G05
T1
X216.7Y-115.25
T2
X237.5Y-115.25
T3
X149.8Y-97.475
X204.75Y-114.25
M30
