#!/usr/bin/env python3
"""Generate combined quotes.h for mood-selector from all octopus quote lists."""

import sys
import os

# Add project root so we can import devtool's quote data
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'DevTool'))

# We need to extract quotes without importing the full tkinter GUI.
# Read devtool.py source and exec just the quote list definitions.

devtool_path = os.path.join(os.path.dirname(__file__), '..', '..', 'DevTool', 'devtool.py')

with open(devtool_path, 'r') as f:
    source = f.read()

# Extract quote list blocks - they're top-level lists defined before the class
# We'll exec them in a controlled namespace
namespace = {}

# Find and exec each quote list
import re
quote_vars = [
    'SASSY_QUOTES', 'SUPPORTIVE_QUOTES', 'ANGRY_QUOTES',
    'CONSPIRATORIAL_QUOTES', 'SAD_QUOTES', 'CHAOTIC_QUOTES',
    'HUNGRY_QUOTES', 'TIRED_QUOTES', 'SLAPHAPPY_QUOTES',
    'LAZY_QUOTES', 'FAT_QUOTES', 'CHILL_QUOTES',
    'HORNY_QUOTES', 'EXCITED_QUOTES', 'NOSTALGIC_QUOTES',
    'HOMESICK_QUOTES',
]

for var in quote_vars:
    # Find the start of the list
    pattern = rf'^{var}\s*=\s*\['
    match = re.search(pattern, source, re.MULTILINE)
    if not match:
        print(f"WARNING: Could not find {var}")
        continue

    start = match.start()
    # Find matching closing bracket
    depth = 0
    i = source.index('[', start)
    for j in range(i, len(source)):
        if source[j] == '[':
            depth += 1
        elif source[j] == ']':
            depth -= 1
            if depth == 0:
                end = j + 1
                break

    block = f"{var} = {source[i:end]}"
    exec(block, namespace)

mood_map = {
    None: 0, "weird": 1, "unhinged": 2, "angry": 3, "sad": 4,
    "chaotic": 5, "hungry": 6, "tired": 7, "slaphappy": 8,
    "lazy": 9, "fat": 10, "chill": 11, "horny": 12,
    "excited": 13, "nostalgic": 14, "homesick": 15,
}

# Map quote lists to their default moods
configs = [
    ('SASSY_QUOTES',          None),
    ('SUPPORTIVE_QUOTES',     None),
    ('ANGRY_QUOTES',          'angry'),
    ('CONSPIRATORIAL_QUOTES', 'weird'),
    ('SAD_QUOTES',            'sad'),
    ('CHAOTIC_QUOTES',        'chaotic'),
    ('HUNGRY_QUOTES',         'hungry'),
    ('TIRED_QUOTES',          'tired'),
    ('SLAPHAPPY_QUOTES',      'slaphappy'),
    ('LAZY_QUOTES',           'lazy'),
    ('FAT_QUOTES',            'fat'),
    ('CHILL_QUOTES',          'chill'),
    ('HORNY_QUOTES',          'horny'),
    ('EXCITED_QUOTES',        'excited'),
    ('NOSTALGIC_QUOTES',      'nostalgic'),
    ('HOMESICK_QUOTES',       'homesick'),
]

def parse_quote(raw):
    """Parse a quote entry — either a string or a (string, mood) tuple."""
    if isinstance(raw, tuple):
        return raw[0], raw[1]
    return raw, None

# Collect all quotes
all_quotes = []
for var_name, default_mood in configs:
    quotes = namespace.get(var_name, [])
    for raw in quotes:
        text, mood = parse_quote(raw)
        mood = mood or default_mood
        mood_id = mood_map.get(mood, 0)
        all_quotes.append((text, mood_id))

print(f"Total quotes: {len(all_quotes)}")

# Write quotes.h
header_path = os.path.join(os.path.dirname(__file__), 'quotes.h')
with open(header_path, 'w') as f:
    f.write("/* Auto-generated by mood-selector/generate_quotes.py — do not edit */\n")
    f.write("#ifndef QUOTES_H\n#define QUOTES_H\n\n")
    f.write("#include <stdint.h>\n\n")
    f.write('#define TAGLINE "~ MOOD SELECTOR ~"\n')
    f.write(f"#define QUOTE_COUNT {len(all_quotes)}\n\n")
    f.write("typedef struct { const char *text; uint8_t mood; } Quote;\n\n")
    f.write(f"static const Quote quotes[QUOTE_COUNT] = {{\n")

    for text, mood_id in all_quotes:
        escaped = text.replace('\\', '\\\\').replace('"', '\\"')
        f.write(f'    {{"{escaped}", {mood_id}}},\n')

    f.write("};\n\n")
    f.write("#endif /* QUOTES_H */\n")

size_kb = os.path.getsize(header_path) / 1024
print(f"Wrote quotes.h ({size_kb:.1f} KB, {len(all_quotes)} quotes)")
