/**
 * Octopus Banner — pixel-art octopus with cycling quotes
 *
 * Draws two octopus variants (Sassy + Supportive) on canvas elements
 * and cycles through their quote pools with a typewriter effect.
 */
(function () {
  "use strict";

  // ── Octopus body pixel data (run-length encoded) ──
  // Format: [y, [[x0,x1], ...]] — same data as the DevTool Python source
  var BODY = [
    [10,[[22,48]]],[11,[[18,52]]],[12,[[16,54]]],[13,[[14,56]]],
    [14,[[13,57]]],[15,[[12,58]]],[16,[[11,59]]],[17,[[10,60]]],
    [18,[[10,60]]],[19,[[9,61]]],[20,[[9,61]]],[21,[[9,61]]],
    [22,[[9,61]]],[23,[[9,61]]],[24,[[9,61]]],[25,[[9,61]]],
    [26,[[9,61]]],[27,[[9,61]]],[28,[[10,60]]],[29,[[10,60]]],
    [30,[[10,60]]],[31,[[10,60]]],[32,[[10,60]]],[33,[[10,60]]],
    [34,[[10,60]]],[35,[[10,60]]],[36,[[10,60]]],[37,[[10,60]]],
    [38,[[10,60]]],[39,[[10,60]]],[40,[[10,60]]],[41,[[11,59]]],
    [42,[[11,59]]],[43,[[12,58]]],[44,[[13,57]]],[45,[[14,56]]],
    [46,[[12,58]]],[47,[[11,59]]],[48,[[10,60]]],[49,[[10,60]]],
    [50,[[11,59]]],[51,[[12,58]]],[52,[[13,57]]],[53,[[14,56]]],
    [54,[[15,55]]],
    // Tentacles
    [55,[[10,17],[21,28],[32,39],[43,50],[54,61]]],
    [56,[[8,15],[19,26],[30,37],[45,52],[56,63]]],
    [57,[[7,14],[18,24],[29,35],[47,53],[58,64]]],
    [58,[[6,12],[19,25],[31,37],[46,52],[57,63]]],
    [59,[[7,13],[21,27],[33,39],[44,50],[55,61]]],
    [60,[[8,14],[20,26],[31,37],[43,49],[54,60]]],
    [61,[[9,14],[18,24],[30,36],[44,50],[56,62]]],
    [62,[[8,13],[17,22],[31,37],[46,52],[57,63]]],
    [63,[[7,12],[18,23],[33,38],[45,51],[55,61]]],
    [64,[[8,13],[20,25],[32,37],[43,48],[54,59]]],
    [65,[[9,14],[19,24],[30,35],[44,49],[55,60]]],
    [66,[[10,14],[17,22],[31,36],[46,51],[57,62]]],
    [67,[[9,13],[18,22],[33,37],[45,50],[56,61]]],
    [68,[[8,12],[19,23],[32,36],[43,48],[54,59]]],
    [69,[[9,13],[21,25],[30,34],[44,48],[55,59]]],
    [70,[[10,14],[20,24],[31,35],[46,50],[57,61]]],
    [71,[[11,14],[18,22],[33,37],[45,49],[56,60]]],
    [72,[[10,13],[19,22],[32,35],[43,47],[54,58]]],
    [73,[[9,12],[20,23],[30,33],[44,47],[55,58]]],
    [74,[[10,13],[21,24],[31,34],[46,49],[57,60]]],
    [75,[[11,14],[20,23],[33,36],[45,48],[56,59]]],
    [76,[[12,14],[19,22],[32,35],[43,46],[54,57]]],
    [77,[[11,13],[20,22],[30,33],[44,46],[55,57]]],
    [78,[[10,12],[21,23],[31,33],[45,47],[56,58]]],
    [79,[[11,13],[22,24],[32,34],[44,46],[55,57]]],
    [80,[[12,14],[21,23],[33,35],[43,45],[54,56]]]
  ];

  // Eye sockets (white circles), pupils (black dots), highlights (white sparkle)
  function circlePixels(cx, cy, rSq) {
    var r = Math.ceil(Math.sqrt(rSq));
    var pts = [];
    for (var dy = -r; dy <= r; dy++)
      for (var dx = -r; dx <= r; dx++)
        if (dx * dx + dy * dy <= rSq)
          pts.push([cx + dx, cy + dy]);
    return pts;
  }

  var EYES = circlePixels(22, 25, 16).concat(circlePixels(48, 25, 16));
  var PUPILS = circlePixels(23, 26, 4).concat(circlePixels(49, 26, 4));
  var HIGHLIGHTS = circlePixels(20, 23, 1).concat(circlePixels(46, 23, 1));

  // Smirk mouth
  function smirkPixels() {
    var outline = [], interior = [];
    for (var x = 28; x < 44; x++) {
      var t = (x - 28) / 15.0;
      var tilt = -2 + t * 4;
      var v = 2 * t - 1;
      var arc = Math.abs(v) < 1 ? 5 * Math.sqrt(1 - v * v) : 0;
      var yc = 39 + tilt + arc;
      outline.push([x, Math.floor(yc - 1)]);
      outline.push([x, Math.floor(yc + 1)]);
      interior.push([x, Math.floor(yc)]);
    }
    return { outline: outline, interior: interior };
  }

  // ── Draw octopus on a canvas ──
  function drawOctopus(canvas, scale) {
    var s = scale || 2;
    canvas.width = 70 * s;
    canvas.height = 85 * s;
    var ctx = canvas.getContext("2d");

    // Pixel buffer (70x85 region — the octopus lives in roughly x:5-65, y:8-82)
    var W = 70, H = 85, offX = 0, offY = -5;
    var buf = [];
    for (var i = 0; i < H; i++) buf[i] = new Uint8Array(W);

    // Body
    BODY.forEach(function (row) {
      var y = row[0] + offY;
      if (y < 0 || y >= H) return;
      row[1].forEach(function (span) {
        for (var x = Math.max(0, span[0] + offX); x <= Math.min(W - 1, span[1] + offX); x++)
          buf[y][x] = 1;
      });
    });

    // Eyes (white)
    EYES.forEach(function (p) {
      var x = p[0] + offX, y = p[1] + offY;
      if (x >= 0 && x < W && y >= 0 && y < H) buf[y][x] = 0;
    });

    // Pupils (black)
    PUPILS.forEach(function (p) {
      var x = p[0] + offX, y = p[1] + offY;
      if (x >= 0 && x < W && y >= 0 && y < H) buf[y][x] = 1;
    });

    // Highlights (white)
    HIGHLIGHTS.forEach(function (p) {
      var x = p[0] + offX, y = p[1] + offY;
      if (x >= 0 && x < W && y >= 0 && y < H) buf[y][x] = 0;
    });

    // Smirk
    var smirk = smirkPixels();
    smirk.interior.forEach(function (p) {
      var x = p[0] + offX, y = p[1] + offY;
      if (x >= 0 && x < W && y >= 0 && y < H) buf[y][x] = 0;
    });
    smirk.outline.forEach(function (p) {
      var x = p[0] + offX, y = p[1] + offY;
      if (x >= 0 && x < W && y >= 0 && y < H) buf[y][x] = 1;
    });

    // Render to canvas
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    for (var y = 0; y < H; y++)
      for (var x = 0; x < W; x++)
        if (buf[y][x]) {
          ctx.fillStyle = "#cdd6f4";
          ctx.fillRect(x * s, y * s, s, s);
        }
  }

  // ── Quotes ──
  var SASSY = [
    "WIFI IS JUST SPICY AIR.",
    "FISH ARE JUST WET BIRDS.",
    "I DONT HAVE BONES AND THATS A FLEX.",
    "MATTRESSES ARE BODY SHELVES.",
    "THE OCEAN IS JUST SKY JUICE.",
    "SLEEP IS FREE DEATH TRIAL.",
    "STAIRS ARE JUST BROKEN ESCALATORS.",
    "THE FLOOR IS JUST A BIG SHELF.",
    "DOORS ARE WALLS THAT GAVE UP.",
    "EGGS ARE JUST BONELESS CHICKENS.",
    "IM 90% WATER. IM BASICALLY A SPLASH.",
    "SAND IS JUST ANGRY ROCKS.",
    "TREES ARE JUST GROUND HAIR.",
    "LAVA IS JUST EARTH SAUCE.",
    "MATH IS JUST SPICY COUNTING.",
    "SOCKS ARE JUST FOOT PRISONS.",
    "A BURRITO IS A SLEEPING BAG FOR FOOD.",
    "INK IS MY DEFENSE MECHANISM. AND COMEDY.",
    "8 ARMS AND ZERO PATIENCE.",
    "SPAGHETTI IS JUST BONELESS TENTACLES.",
    "JELLYFISH ARE JUST OCEAN GHOSTS.",
    "I HUG THINGS 4X BETTER THAN YOU.",
    "BLANKETS ARE JUST ADULT SWADDLES.",
    "POCKETS ARE JUST BUILT IN BAGS.",
    "CLAPPING IS JUST HITTING YOURSELF BECAUSE YOU LIKE SOMETHING.",
    "A PILLOW IS JUST A SOFT RECTANGLE YOU DROOL ON.",
    "SHOES ARE JUST OUTDOOR SOCKS WITH AMBITION.",
    "CANDLES ARE JUST FANCY FIRE STICKS FOR SAD PEOPLE.",
    "A LAWN IS JUST A CARPET THAT NEEDS WATER.",
    "UNDERWEAR IS JUST A SECOND SKIN YOU CHOSE.",
    "TEETH ARE THE ONLY BONES YOU HAVE TO BRUSH.",
    "SWEATING IS YOUR BODY CRYING BECAUSE YOU MOVED TOO MUCH.",
    "HAIR IS JUST HEAD STRINGS.",
    "A WALLET IS JUST A POCKET FOR YOUR POCKET.",
    "EYEBROWS ARE JUST FOREHEAD MUSTACHES.",
    "NOSES ARE JUST FACE HANDLES.",
    "TOENAILS ARE JUST FOOT CHIPS.",
    "A GARAGE IS A HOUSE FOR YOUR CAR. YOUR CAR HAS A HOUSE.",
    "COTTON CANDY IS JUST EDIBLE INSULATION.",
    "A CEMETERY IS JUST A PEOPLE GARDEN.",
    "NIPPLES ARE JUST CHEST BUTTONS THAT DO NOTHING.",
    "A CALENDAR IS JUST A COUNTDOWN TO YOUR DEATH WITH PICTURES.",
    "IM TOO PRETTY FOR THIS DAMN OCEAN.",
    "DONT TALK TO ME BEFORE MY KELP COFFEE.",
    "I DIDNT ASK TO BE THIS FABULOUS.",
    "CATCH ME OUTSIDE THE REEF. HOW BOUT DAT.",
    "YOUR OPINION MEANS LESS THAN PLANKTON TO ME.",
    "SORRY CANT HEAR YOU OVER MY 8 ARM ENERGY.",
    "WHAT THE SHELL DID YOU JUST SAY TO ME.",
    "YOURE ABOUT AS USEFUL AS A SCREEN DOOR ON A SUBMARINE.",
    "I HAVE 3 HEARTS AND NONE OF THEM CARE.",
    "BOLD WORDS FROM SOMEONE WITH ONLY 2 ARMS.",
    "OH HELL NO. ABSOLUTELY NOT. NEXT.",
    "THE AUDACITY. THE DAMN AUDACITY.",
    "I DIDNT CRAWL OUT OF THE PRIMORDIAL OOZE FOR THIS BULLSHIT.",
    "TALK TO THE TENTACLE CAUSE THE FACE AINT LISTENING.",
    "I HAVE MORE ARMS THAN YOU HAVE BRAIN CELLS.",
    "YOURE GIVING OFF STRONG BARNACLE ENERGY RIGHT NOW.",
    "IM NOT BEING RUDE IM BEING EFFICIENT WITH MY DISGUST.",
    "I COULD MULTITASK CIRCLES AROUND YOUR ENTIRE FAMILY.",
    "MY RESTING FACE HAS MORE PERSONALITY THAN YOUR BEST DAY.",
    "I DIDNT CHOOSE THE TENTACLE LIFE. IT CHOSE ME AND I SLAYED.",
    "IM NOT ARGUING IM JUST EXPLAINING WHY YOURE WRONG. WITH 8 ARMS.",
    "SIT DOWN. I SAID SIT. GOOD. NOW LISTEN.",
    "IMAGINE BEING THAT CONFIDENT WITH ONLY 4 LIMBS.",
    "I COULD OUT-SASS A SEA CUCUMBER AND THOSE THINGS LITERALLY EXPEL THEIR GUTS.",
    "BIRDS ARENT REAL. THEY CHARGE ON POWER LINES!",
    "PIGEONS ARE DRONES. WAKE UP SHEEPLE.",
    "CLOUDS ARE GOVERNMENT PILLOWS.",
    "THE MOON IS JUST THE BACK OF THE SUN.",
    "GRAVITY IS A SUBSCRIPTION SERVICE.",
    "MIRRORS ARE JUST WATER THAT TRIED HARDER.",
    "YOUR SKELETON IS WET RIGHT NOW. THINK ABOUT IT.",
    "OCTOBER HAS NO OCTOS IN IT. SUS AS HELL.",
    "TREES ARE SURVEILLANCE ANTENNAS. LOOK IT UP.",
    "RAIN IS JUST THE SKY PEEING. PROVE ME WRONG.",
    "THE ALPHABET IS IN THAT ORDER FOR A DAMN REASON.",
    "BELLY BUTTONS ARE JUST OLD MOUTHS.",
    "YAWNING IS YOUR SKULL TRYING TO ESCAPE.",
    "SHADOWS ARE JUST 2D VERSIONS OF YOU SPYING.",
    "DEJA VU IS THE SIMULATION BUFFERING.",
    "HICCUPS ARE YOUR BODY GLITCHING.",
    "SNEEZING IS YOUR BRAIN REBOOTING AND NOBODY QUESTIONS IT.",
    "TEETH ARE JUST MOUTH ROCKS THAT FELL OUT OF YOUR SKULL.",
    "FINGERPRINTS ARE JUST SKIN BARCODES THE GOVERNMENT PRE-INSTALLED.",
    "SLEEP PARALYSIS IS JUST YOUR FREE TRIAL OF DEATH.",
    "GOOSEBUMPS ARE YOUR BODY TRYING TO GROW FEATHERS BACK.",
    "ALLERGIES ARE YOUR IMMUNE SYSTEM HAVING A DAMN PANIC ATTACK OVER FLOWERS.",
    "BLINKING IS JUST YOUR EYES CLAPPING.",
    "YOUR TONGUE JUST SITS IN YOUR MOUTH LIKE A FAT LITTLE SLUG.",
    "BABIES ARE JUST SMALL DRUNK PEOPLE WHO DONT PAY RENT.",
    "ELEVATORS ARE JUST TRUST FALLS WITH A BUILDING.",
    "HOSPITALS ARE JUST BODY REPAIR SHOPS WITH BAD FOOD.",
    "FIRE TRUCKS ARE ACTUALLY WATER TRUCKS. BIG FIRE DOESNT WANT YOU TO KNOW.",
    "YOUR EARS NEVER CLOSE. YOURE HEARING EVERYTHING ALL THE TIME.",
    "ANKLES ARE JUST WRIST KNOCKOFFS.",
    "COUGHING IS JUST YOUR LUNGS THROWING UP.",
    "FRIDGES ARE JUST COLD CLOSETS FOR DEAD THINGS.",
    "THE DEEP STATE RUNS APPLEBEES.",
    "MATTRESS FIRM IS A MONEY LAUNDERING FRONT.",
    "FINLAND DOESNT EXIST. GOOGLE IT.",
    "WYOMING IS JUST A GOVERNMENT PRANK.",
    "AUSTRALIA IS UPSIDE DOWN AND FAKE.",
    "THE BERMUDA TRIANGLE IS MY VACATION HOME.",
    "5G TURNED MY NEIGHBOR INTO A ROUTER.",
    "THE TITANIC WAS AN INSURANCE SCAM.",
    "DENVER AIRPORT IS AN ILLUMINATI CLUBHOUSE.",
    "BIGFOOT IS REAL AND HES A DAMN GENTLEMAN.",
    "FLAT EARTHERS ARE SECRETLY ROUND.",
    "CROP CIRCLES ARE JUST ALIEN DOODLES.",
    "THE QUEEN WAS A LIZARD PERSON AND SHE WASNT EVEN HIDING IT.",
    "AREA 51 IS JUST WHERE THE GOVERNMENT KEEPS THE GOOD SNACKS.",
    "CHEMTRAILS ARE JUST SKY SEASONING.",
    "THE ILLUMINATI RUNS COSTCO. FREE SAMPLES ARE MIND CONTROL.",
    "STONEHENGE IS JUST AN ANCIENT IKEA THAT NOBODY FINISHED BUILDING.",
    "THE PYRAMIDS WERE BUILT BY CATS. EGYPTIANS JUST TOOK CREDIT.",
    "NEW ZEALAND IS A PAID ACTOR.",
    "GIRAFFES ARE GOVERNMENT SURVEILLANCE CAMERAS WITH LEGS.",
    "THE MOON LANDING WAS REAL BUT THE MOON IS FAKE.",
    "CANADA IS JUST AMERICAS HAT AND ITS IN ON IT.",
    "THE HADRON COLLIDER IS JUST A BIG ASS BEYBLADE.",
    "BLUETOOTH IS WITCHCRAFT AND IM TIRED OF PRETENDING ITS NOT.",
    "WHAT IF YOUR LEGS DIDNT KNOW THEY WERE LEGS.",
    "I JUST REALIZED WATER IS BONELESS ICE.",
    "EVERY ROOM IS AN ESCAPE ROOM IF YOU SUCK.",
    "CORN IS JUST FRUIT WITH EXTRA STEPS.",
    "SOUP IS JUST WET SALAD. FIGHT ME.",
    "ELEVATORS ARE JUST ROOMS THAT MOVE. WHAT THE HELL.",
    "COFFINS ARE UNDERGROUND TINY HOMES.",
    "A FLY WITHOUT WINGS IS JUST A WALK.",
    "GLOVES ARE JUST HAND SOCKS. HAND. SOCKS.",
    "A KEYBOARD IS JUST AN ORGANIZED ALPHABET.",
    "THE SUN IS A DEADLY LAZER BUT WE JUST VIBE.",
    "IF NOTHING IS IMPOSSIBLE THEN IS IT POSSIBLE FOR SOMETHING TO BE IMPOSSIBLE.",
    "WHAT IF OXYGEN IS ACTUALLY POISONOUS AND JUST TAKES 80 YEARS TO KILL US.",
    "WHEN YOU CLEAN A VACUUM CLEANER YOU BECOME THE VACUUM CLEANER.",
    "YOUR AGE IS JUST THE NUMBER OF LAPS YOUVE DONE AROUND A GIANT FIREBALL.",
    "A DENTIST APPOINTMENT IS JUST PAYING SOMEONE TO FINGERBANG YOUR MOUTH.",
    "MAYBE DOGS FETCH THE BALL BECAUSE THEY THINK YOU LIKE THROWING IT.",
    "WHAT IF PLANTS ARE FARMING US BY GIVING US OXYGEN UNTIL WE DECOMPOSE.",
    "A BOOMERANG THAT DOESNT COME BACK IS JUST A STICK.",
    "WHOEVER NAMED THE FIREPLACE REALLY WASNT TRYING THAT HARD.",
    "A SUNSET IS JUST THE SUN RAGE QUITTING FOR THE DAY.",
    "THE FIRST PERSON TO HEAR A PARROT TALK MUST HAVE LOST THEIR DAMN MIND.",
    "A PAPER CUT IS A TREES LAST REVENGE.",
    "THE PERSON WHO DISCOVERED MILK WAS DOING SOMETHING DEEPLY SUSPICIOUS TO THAT COW.",
    "THE MARIANA TRENCH IS WHERE GOD DROPPED HIS KEYS.",
    "THERE ARE THINGS IN THE DEEP OCEAN THAT WOULD MAKE GOD CRY.",
    "THE OCEAN IS JUST A BIG ASS SOUP AND WERE ALL CROUTONS.",
    "ANGLERFISH INVENTED CATFISHING AND NOBODY GIVES THEM CREDIT.",
    "WHALES ARE JUST FAT SUBMARINES CHANGE MY DAMN MIND.",
    "THE KRAKEN IS REAL AND ITS MY COUSIN STEVE.",
    "CORAL REEFS ARE JUST UNDERWATER CITIES WE KEEP MURDERING.",
    "DOLPHINS ARE PSYCHOPATHS WITH GOOD PR.",
    "SHRIMP ON A TREADMILL WAS FUNDED BY YOUR TAXES.",
    "THE OCEAN FLOOR IS LESS MAPPED THAN MARS AND THAT PISSES ME OFF.",
    "HAGFISH SNEEZE SLIME WHEN STRESSED AND HONESTLY SAME.",
    "BARNACLES HAVE THE LARGEST JUNK TO BODY RATIO OF ANY ANIMAL. LOOK IT UP.",
    "LOBSTERS PEE OUT OF THEIR FACES TO ATTRACT MATES. RESPECT THE HUSTLE.",
    "SEA CUCUMBERS BREATHE THROUGH THEIR BUTTHOLES. I WISH I WAS LYING.",
    "MANTIS SHRIMP PUNCH SO HARD THEY BOIL THE WATER AROUND THEIR FIST.",
    "STARFISH DONT HAVE BLOOD. THEY PUMP SEAWATER THROUGH THEIR BODY. METAL AS HELL.",
    "THERE IS A JELLYFISH THAT IS LITERALLY IMMORTAL. WHAT THE HELL.",
    "THE PISTOL SHRIMP SNAPS SO LOUD IT CREATES A TINY SUN. A TINY DAMN SUN.",
    "GREENLAND SHARKS CAN LIVE FOR 500 YEARS. FIVE HUNDRED. WHAT ARE THEY DOING.",
    "CLOWNFISH CAN CHANGE GENDER. FINDING NEMO LIED TO ALL OF US.",
    "NOTHING MATTERS AND THATS ACTUALLY PRETTY DAMN FREEING.",
    "WE ARE ALL JUST MEAT COMPUTERS HAVING A BAD TIME.",
    "TIME IS FAKE. CLOCKS ARE A CONSPIRACY.",
    "WHAT IF WE ARE ALL JUST NPCS IN SOMEONES GAME.",
    "THE VOID STARED BACK AND IT WINKED AT ME.",
    "REALITY IS A SHARED HALLUCINATION AND THE RENT IS TOO DAMN HIGH.",
    "IF ATOMS ARE MOSTLY EMPTY SPACE THEN IM MOSTLY NOTHING. COOL.",
    "EVERY SECOND YOU EXIST IS STATISTICALLY INSANE.",
    "THE FACT THAT ANYTHING EXISTS AT ALL IS BATSHIT.",
    "FREE WILL IS JUST ANXIETY WITH A MARKETING TEAM.",
    "YOURE A BRAIN PILOTING A MEAT MECH AND YOURE DOING GREAT I GUESS.",
    "THE UNIVERSE IS 13 BILLION YEARS OLD AND YOU HAVE TO DO TAXES.",
    "YOURE TECHNICALLY A TUBE. MOUTH TO BUTT. JUST A FANCY TUBE.",
    "YOUR BODY REPLACES ITSELF EVERY 7 YEARS. YOURE NOT EVEN YOU ANYMORE.",
    "CONSCIOUSNESS IS JUST MATTER EXPERIENCING ITSELF AND BEING STRESSED ABOUT IT.",
    "WE ARE ALL JUST SKELETONS WEARING MEAT COSTUMES PRETENDING EVERYTHINGS FINE.",
    "YOU DIDNT EXIST FOR BILLIONS OF YEARS AND THEN BOOM HERE YOU ARE READING THIS.",
    "ENTROPY MEANS EVERYTHING IS SLOWLY FALLING APART INCLUDING THIS SENTENCE.",
    "EVERY ATOM IN YOUR BODY WAS FORGED IN A DYING STAR AND NOW YOURE SCROLLING.",
    "THE HEAT DEATH OF THE UNIVERSE IS COMING AND THERE IS NO ESCAPE. ANYWAY HOW ARE YOU.",
    "I HAVE SEEN THE FACE OF GOD AND IT WAS AN OCTOPUS.",
    "THEY PUT CHEMICALS IN THE WATER TO MAKE THE DAMN FROGS GAY.",
    "EVERYTHING IS CAKE. LITERALLY EVERYTHING. CUT INTO YOUR DESK.",
    "THE SIMULATION IS RUNNING OUT OF RAM AND ITS SHOWING.",
    "TUPAC IS ALIVE AND WORKING AT A TARGET IN OHIO.",
    "BIRDS WORK FOR THE BOURGEOISIE.",
    "EARTH IS A REALITY TV SHOW FOR ALIENS AND WE ARE LOSING.",
    "MOTHMAN IS JUST A BIG MOTH WHO BELIEVES IN HIMSELF.",
    "SKINWALKER RANCH IS JUST A PETTING ZOO FOR CRYPTIDS.",
    "FLUORIDE IN WATER MAKES YOU FORGET THAT BIRDS ARENT REAL.",
    "CICADAS SLEEP FOR 17 YEARS THEN SCREAM FOR SEX AND DIE. LIVING THE DREAM.",
    "THERE IS A FUNGUS THAT TURNS ANTS INTO ZOMBIES. NATURE IS UNHINGED.",
    "DOGS CAN SMELL TIME. TIME. YOUR DOG KNOWS WHAT 3PM SMELLS LIKE.",
    "CROWS HOLD GRUDGES AND TELL THEIR FRIENDS ABOUT YOU. SLEEP TIGHT.",
    "TREES TALK TO EACH OTHER THROUGH FUNGUS. THE FOREST IS GOSSIPING ABOUT YOU.",
    "A GROUP OF FLAMINGOS IS CALLED A FLAMBOYANCE AND THATS THE ONLY GOOD THING.",
    "THERE ARE MORE TIGERS IN TEXAS THAN IN THE WILD. TEXAS IS UNHINGED.",
    "PLATYPUSES GLOW UNDER UV LIGHT. WHY. FOR WHO. NOBODY KNOWS.",
    "OCTOPUSES HAVE BEEN CAUGHT PUNCHING FISH FOR NO REASON. HELL YEAH.",
    "WOMBAT POOP IS CUBE SHAPED. GOD WAS HAVING A WEIRD DAY.",
    "I HAVE 3 HEARTS AND ALL OF THEM ARE PETTY.",
    "MY BLOOD IS LITERALLY BLUE. IM ROYALTY. BOW.",
    "I CAN CHANGE COLOR. CAN YOU DO THAT. NO. SIT DOWN.",
    "I CAN FIT THROUGH ANY HOLE BIGGER THAN MY BEAK. TRY ME.",
    "I ONCE UNSCREWED A JAR FROM THE INSIDE. WHAT HAVE YOU DONE.",
    "MY BRAIN IS SHAPED LIKE A DONUT AND ITS STILL SMARTER THAN YOU.",
    "I TASTE WITH MY SUCKERS. EVERYTHING I TOUCH I TASTE. ITS A LOT.",
    "MY ARMS GROW BACK. CAN YOURS DO THAT. DIDNT THINK SO.",
    "I HAVE ZERO BONES. ZERO. AND I STILL HAVE MORE SPINE THAN YOU.",
    "I SQUIRT INK WHEN IM SCARED AND I THINK THATS BEAUTIFUL.",
    "I CAN OPEN CHILD-PROOF BOTTLES. YOUR MOVE HUMANS.",
    "MY CAMOUFLAGE IS SO GOOD I SCARE MYSELF SOMETIMES.",
    "I HAVE SEEN THINGS IN THE ABYSS THAT WOULD MELT YOUR PATHETIC LITTLE MIND.",
    "I ESCAPED AN AQUARIUM ONCE. ILL DO IT AGAIN.",
    "EACH OF MY ARMS HAS ITS OWN BRAIN. THATS 9 BRAINS TOTAL YOU ABSOLUTE WALNUT.",
    "I COULD DISASSEMBLE YOUR ENTIRE LIFE WITH 8 ARMS AND ZERO REMORSE.",
    "SCIENTISTS THINK WE MIGHT BE ALIENS. OCTOPUS DNA IS WEIRD AS HELL.",
    "I CAN EDIT MY OWN RNA. I AM MY OWN DAMN SCIENTIST.",
    "MY ANCESTORS PREDATE TREES. TREES. I WAS HERE FIRST YOU LEAFY BITCHES.",
    "I HAVE BEEN OBSERVED USING COCONUT SHELLS AS ARMOR. TACTICAL GENIUS.",
    "WE LITERALLY DREAM. OCTOPUS DREAMS. WHAT THE HELL DO WE DREAM ABOUT.",
    "SOME OF US CARRY JELLYFISH TENTACLES AS WEAPONS. WE ARE NOT PLAYING.",
    "LASAGNA IS JUST SPAGHETTI CAKE.",
    "A HOTDOG IS A TACO. I WILL DIE ON THIS HILL.",
    "CEREAL IS BREAKFAST SOUP AND YOU KNOW IT.",
    "PANCAKES ARE JUST FLAT BREAD WITH AN EGO.",
    "RAISINS ARE JUST GRAPES THAT GAVE UP ON LIFE.",
    "ICE IS JUST WATER WITH COMMITMENT ISSUES.",
    "PICKLES ARE JUST CUCUMBERS THAT WENT THROUGH SOME SHIT.",
    "POPCORN IS JUST CORN HAVING A PANIC ATTACK.",
    "TOAST IS JUST TWICE BAKED BREAD. WHY.",
    "CROUTONS ARE JUST BREAD THAT DIED AND CAME BACK HARDER.",
    "CHEESE IS JUST A LOAF OF MILK.",
    "JELLY IS JUST FRUIT THAT LOST ITS STRUCTURAL INTEGRITY.",
    "BACON IS JUST PIG JERKY WITH BETTER PR.",
    "AN EGG SALAD SANDWICH IS JUST CHICKEN BETWEEN BREAD WITH EXTRA STEPS.",
    "SALSA IS JUST AN ANGRY SMOOTHIE.",
    "GUACAMOLE IS JUST AVOCADO THAT LOST A FIGHT.",
    "TEA IS JUST LEAF SOUP.",
    "COFFEE IS JUST BEAN BROTH FOR PEOPLE WHO HATE THEMSELVES.",
    "A QUESADILLA IS JUST A MEXICAN GRILLED CHEESE. CHANGE MY MIND.",
    "MASHED POTATOES ARE JUST IRISH GUACAMOLE.",
    "RANCH DRESSING IS AMERICAS HOLLANDAISE AND I WILL NOT ELABORATE.",
    "SUSHI IS JUST A FISH SLEEPING BAG.",
    "A POPSICLE IS JUST A DOMESTICATED ICICLE.",
    "YOGURT IS JUST MILK THATS BEEN THROUGH SOME STUFF."
  ];

  var SUPPORTIVE = [
    "YOU ARE DOING SO DAMN GOOD RIGHT NOW.",
    "HEY. HEY YOU. YOURE INCREDIBLE. DEAL WITH IT.",
    "I HAVE 8 ARMS AND ID USE THEM ALL TO HUG YOU.",
    "YOURE THE REASON I BELIEVE IN LAND PEOPLE.",
    "GO DRINK SOME WATER YOU BEAUTIFUL DISASTER.",
    "YOU ABSOLUTE LEGEND. I MEAN IT. LEGEND.",
    "YOUR EXISTENCE IS MY FAVORITE THING TODAY.",
    "IM SO PROUD OF YOU IT MAKES MY TENTACLES TINGLE.",
    "YOU WOKE UP TODAY AND CHOSE BEING AWESOME.",
    "YOURE DOING GREAT SWEETIE AND I WILL FIGHT ANYONE WHO SAYS OTHERWISE.",
    "YOU DESERVE A STANDING OVATION JUST FOR GETTING OUT OF BED.",
    "WHOEVER RAISED YOU DID A DAMN GOOD JOB. OR YOU DID. EITHER WAY BRAVO.",
    "YOU JUST EXISTING IMPROVED THE AVERAGE VIBE OF THIS PLANET.",
    "IF KINDNESS HAD A FACE IT WOULD BE YOURS. PROBABLY.",
    "THE WORLD IS BETTER BECAUSE YOURE IN IT AND THATS NOT EVEN DEBATABLE.",
    "YOU ARE SOMEONES REASON TO SMILE TODAY AND THATS BEAUTIFUL AS HELL.",
    "I BET YOUR MOM CRIES HAPPY TEARS ABOUT YOU. I WOULD.",
    "YOU MAKE THE SUN LOOK LIKE A FLICKERING NIGHTLIGHT.",
    "YOUR LAUGH COULD CURE DISEASES AND I WILL NOT BE TAKING QUESTIONS.",
    "IF THERE WAS AN AWARD FOR BEING A GOOD HUMAN YOUD WIN EVERY DAMN YEAR.",
    "IF LIFE GIVES YOU LEMONS I WILL STRANGLE LIFE FOR YOU.",
    "YOU COULD BENCH PRESS MY EMOTIONS RIGHT NOW.",
    "YOURE NOT A MESS YOURE A MASTERPIECE WITH EXTRA TEXTURE.",
    "I WOULD COMMIT CRIMES FOR YOUR HAPPINESS. SMALL ONES.",
    "THE UNIVERSE MADE YOU ON PURPOSE AND I RESPECT THE HELL OUT OF THAT.",
    "LISTEN. YOURE A SNACK. AN ENTIRE BUFFET ACTUALLY.",
    "YOUR VIBE IS IMMACULATE AND ANYONE WHO DISAGREES CAN CATCH THESE ARMS.",
    "I BELIEVE IN YOU MORE THAN I BELIEVE IN DRY LAND.",
    "YOURE THE MAIN CHARACTER AND EVERYONE ELSE IS AN NPC.",
    "IF YOURE READING THIS CONGRATS YOURE AMAZING AS HELL.",
    "IF ANYONE MAKES YOU SAD I WILL RELEASE THE INK CLOUD OF VENGEANCE.",
    "YOUR ENERGY IS SO POWERFUL IT COULD RESTART A DEAD CAR BATTERY.",
    "I WOULD CRAWL ACROSS AN ENTIRE DESERT FOR YOU AND I NEED WATER TO LIVE.",
    "IF YOU WERE A CANDLE YOUD SMELL LIKE VICTORY AND CINNAMON ROLLS.",
    "I WOULD FISTFIGHT A SEAGULL FOR YOU AND THOSE THINGS ARE VICIOUS.",
    "YOUR SMILE HAS MORE WATTAGE THAN A DAMN LIGHTHOUSE.",
    "I BELIEVE IN YOU SO HARD MY SUCKERS ARE TINGLING.",
    "YOU COULD TALK A SHARK INTO GOING VEGAN WITH THAT CHARM.",
    "IF GOOD VIBES WERE ILLEGAL YOUD BE ON THE FBIS MOST WANTED LIST.",
    "YOU HAVE THE SAME ENERGY AS FINDING TWENTY DOLLARS IN OLD JEANS.",
    "STOP DOUBTING YOURSELF BEFORE I INK ON YOUR PROBLEMS.",
    "YOU DIDNT COME THIS FAR TO ONLY COME THIS FAR.",
    "HATERS GONNA HATE BUT YOU GONNA SLAY.",
    "YOURE NOT TIRED YOURE ON THE VERGE OF GREATNESS.",
    "FAILURE IS JUST SUCCESS IN A REALLY UGLY OUTFIT.",
    "GET UP BESTIE WE HAVE BUTTS TO KICK TODAY.",
    "YOUR POTENTIAL IS SCARIER THAN THE DEEP OCEAN.",
    "IM 90% WATER AND 100% ROOTING FOR YOU.",
    "EVERY DAY YOU WAKE UP IS ANOTHER DAY TO BE A BADASS.",
    "YOU ARE LITERALLY TOO POWERFUL TO GIVE UP NOW.",
    "THEY SAID YOU COULDNT DO IT. THEY WERE WRONG. THEY ARE ALWAYS WRONG.",
    "YOURE BUILT DIFFERENT AND I MEAN THAT IN THE MOST COMPLIMENTARY WAY.",
    "YOUR COMEBACK STORY IS GOING TO BE LEGENDARY.",
    "IF YOURE GOING THROUGH HELL KEEP GOING. AND MAYBE GRAB SNACKS.",
    "YOURE NOT STRUGGLING YOURE LEVELING UP AND BOSS FIGHTS ARE HARD.",
    "YOU HAVE SURVIVED 100% OF YOUR WORST DAYS. THATS A PERFECT RECORD.",
    "EVERY EXPERT WAS ONCE A DISASTER. YOURE RIGHT ON SCHEDULE.",
    "THE ONLY PERSON YOU NEED TO BE BETTER THAN IS YESTERDAY YOU.",
    "YOURE PLAYING ON HARD MODE AND STILL WINNING. RESPECT.",
    "PRESSURE MAKES DIAMONDS AND YOURE ABOUT TO BE THE SHINIEST BITCH IN THE ROOM.",
    "THE AUDACITY OF YOU BEING THIS WONDERFUL. HOW DARE YOU.",
    "YOURE NOT AWKWARD YOURE LIMITED EDITION.",
    "MY THIRD ARM JUST GAVE YOU A THUMBS UP.",
    "YOURE LIKE WIFI BUT FOR GOOD VIBES.",
    "IF YOU WERE A FISH ID THROW YOU BACK. BECAUSE YOURE FREE. GO LIVE.",
    "YOUR HEART IS BIGGER THAN MY ENTIRE HEAD. AND IM MOSTLY HEAD.",
    "I DONT HAVE A SPINE AND EVEN I THINK YOURE BRAVE.",
    "YOU RADIATE THE SAME ENERGY AS A REALLY GOOD SUNSET.",
    "SOMEONE OUT THERE IS SMILING BECAUSE OF YOU. ITS ME. IM SOMEONE.",
    "YOURE THE PLOT TWIST EVERYONE NEEDED.",
    "YOURE THE HUMAN EQUIVALENT OF A PERFECTLY RIPE AVOCADO.",
    "IF YOU WERE A SPICE YOUD BE CAYENNE. HOT AND UNEXPECTED.",
    "YOUR EXISTENCE IS PROOF THAT THE UNIVERSE HAS TASTE.",
    "YOURE GIVING MAIN CHARACTER ENERGY AND THE SOUNDTRACK IS FIRE.",
    "IF CONFIDENCE WAS A FRAGRANCE YOUD BE THE WHOLE DAMN BOTTLE.",
    "YOURE THE REASON ALIENS HAVENT DESTROYED EARTH YET.",
    "YOUR AURA IS SO BRIGHT IT GAVE MY THIRD HEART PALPITATIONS.",
    "YOURE NOT A DIAMOND IN THE ROUGH YOURE THE WHOLE DAMN MINE.",
    "IF COOL WAS A CURRENCY YOUD BE JEFF BEZOS BUT LIKEABLE.",
    "YOURE THE CHEAT CODE TO A BETTER WORLD.",
    "DID YOU EAT TODAY YOU MAGNIFICENT CREATURE.",
    "DRINK WATER OR I SWEAR ON MY TENTACLES.",
    "TAKE A DEEP BREATH. DEEPER. I SAID DEEPER. GOOD.",
    "REST IS NOT LAZY ITS TACTICAL. NOW SIT DOWN.",
    "YOU CANT POUR FROM AN EMPTY CUP SO REFILL YOURSELF DAMMIT.",
    "SLEEP IS NOT FOR THE WEAK ITS FOR THE POWERFUL. GO NAP.",
    "YOUR FEELINGS ARE VALID EVEN THE WEIRD ONES.",
    "BE NICE TO YOURSELF OR ILL SQUIRT INK AT YOU.",
    "ITS OK TO NOT BE OK BUT PLEASE EAT A VEGETABLE.",
    "YOU DESERVE GOOD THINGS AND ALSO A REALLY GOOD SANDWICH.",
    "WHEN WAS THE LAST TIME YOU STRETCHED. DO IT NOW. I SAID NOW.",
    "YOUR BACK HURTS BECAUSE YOURE CARRYING EVERYONE ELSE. PUT THAT DOWN.",
    "LOG OFF. TOUCH GRASS. PET A DOG. COME BACK WHEN YOURE RECHARGED.",
    "YOURE NOT LAZY YOURE RECHARGING. LIKE A PHONE. BUT CUTER.",
    "IF YOU HAVENT CRIED LATELY MAYBE LET ONE OUT. ITS THERAPEUTIC.",
    "STOP DOOM SCROLLING AND GO LOOK AT A TREE. TREES ARE NICE.",
    "YOUR JAW IS CLENCHED RIGHT NOW ISNT IT. RELAX THAT. THERE YOU GO.",
    "UNCLENCH YOUR FISTS BESTIE. THE WAR IS NOT TODAY.",
    "THAT THING YOURE WORRIED ABOUT. ITS GONNA BE OK. I PROMISE.",
    "YOU ARE ALLOWED TO TAKE UP SPACE. YOU ARE ALLOWED TO BE LOUD. YOU ARE ALLOWED.",
    "I WOULD SHARE MY FAVORITE ROCK WITH YOU. THATS HUGE.",
    "YOURE MY FAVORITE HUMAN AND I LIVE IN THE OCEAN.",
    "IF I COULD HIGH FIVE ID DO IT 8 TIMES.",
    "YOU MAKE ME WANT TO COME OUT OF MY HIDING SPOT.",
    "I WROTE YOUR NAME IN INK. ON THE OCEAN FLOOR. FOREVER.",
    "MY HEARTS AND YES I HAVE THREE ALL BEAT FOR YOU.",
    "YOU ARE THE TREASURE THAT PIRATES WERE LOOKING FOR.",
    "I WOULD FIGHT A SHARK FOR YOU. NOT A BIG ONE BUT STILL.",
    "IN A SEA OF FISH YOU ARE THE WHOLE DAMN OCEAN.",
    "YOURE PROOF THAT GOOD THINGS EXIST ON LAND.",
    "I WOULD GIVE YOU MY BEST TENTACLE AND I NEED ALL 8.",
    "I CHANGED COLOR WHEN I SAW YOU. THATS OCTOPUS FOR BLUSHING.",
    "I BUILT A LITTLE ROCK GARDEN ON THE OCEAN FLOOR AND NAMED IT AFTER YOU.",
    "IF I HAD POCKETS ID KEEP A PICTURE OF YOU IN ALL OF THEM.",
    "I WOULD LET YOU TOUCH MY SUCTION CUPS AND THATS INTIMATE AS HELL.",
    "YOU ARE MY FAVORITE THOUGHT AND I HAVE 9 BRAINS TO THINK WITH.",
    "I INKED A LITTLE HEART ON A ROCK FOR YOU. ITS STILL THERE.",
    "IF REINCARNATION IS REAL I WANT TO COME BACK AS YOUR PET.",
    "I DREAMED ABOUT YOU AND OCTOPUS DREAMS ARE WILD SO THATS SAYING SOMETHING.",
    "THE OCEAN IS BIG BUT MY LOVE FOR YOU IS BIGGER AND THATS TERRIFYING.",
    "TODAYS MOOD IS UNSTOPPABLE AND SLIGHTLY UNHINGED.",
    "YOURE ABOUT TO DO SOMETHING AMAZING I CAN FEEL IT IN MY SUCKERS.",
    "PLOT TWIST YOURE THE HERO OF THIS STORY.",
    "SCARED IS JUST EXCITED WITH BAD BRANDING.",
    "YOU MISS 100% OF THE SHOTS YOU DONT TAKE. I MISS 0% BECAUSE 8 ARMS.",
    "NORMALIZE BEING PROUD OF YOURSELF FOR NO REASON.",
    "THE ONLY OPINION THAT MATTERS IS YOURS. AND MINE. AND MINE SAYS YOURE GREAT.",
    "IF PLAN A DIDNT WORK THERE ARE 25 MORE LETTERS. KEEP GOING.",
    "YOURE NOT BEHIND IN LIFE. YOURE ON YOUR OWN DAMN TIMELINE.",
    "THE COMEBACK IS ALWAYS STRONGER THAN THE SETBACK.",
    "TODAY IS A GOOD DAY TO SCARE THE SHIT OUT OF YOUR DOUBTS.",
    "YOURE ONE DECISION AWAY FROM A TOTALLY DIFFERENT LIFE. MAKE IT A GOOD ONE.",
    "THE ONLY LIMITS ARE THE ONES YOU ACCEPT AND I DONT ACCEPT ANY.",
    "YOUR FUTURE SELF IS GONNA BE SO GRATEFUL YOU DIDNT QUIT TODAY.",
    "BURN THE BOATS. THERES NO GOING BACK. ONLY FORWARD. LETS GO.",
    "YOU ARE EXACTLY WHERE YOU NEED TO BE. EVEN IF WHERE YOU ARE SUCKS RIGHT NOW.",
    "COMPARISON IS THE THIEF OF JOY. ROB THAT THIEF BACK.",
    "EVERY FLOWER THAT EVER BLOOMED HAD TO GO THROUGH A LOT OF DIRT FIRST.",
    "DO THE SCARY THING FIRST AND GET SCARED LATER.",
    "YOURE NOT LOST YOURE EXPLORING. AGGRESSIVELY.",
    "I LOVE YOU LIKE THE OCEAN LOVES BEING WET.",
    "YOU ARE THE REASON I HAVE TRUST IN BIPEDS.",
    "IF HUGS WERE CURRENCY ID BE A BILLIONAIRE FOR YOU.",
    "YOURE GLOWING AND NOT IN A RADIOACTIVE WAY. PROBABLY.",
    "I STAN YOU SO HARD ALL 8 ARMS ARE CLAPPING.",
    "YOURE A WHOLE VIBE AND THAT VIBE IS PHENOMENAL.",
    "GO BE GREAT TODAY OR DONT. ILL LOVE YOU EITHER WAY.",
    "MY FAVORITE THING ABOUT YOU IS EVERYTHING.",
    "YOURE NOT JUST A STAR YOURE THE WHOLE CONSTELLATION.",
    "KEEP GOING BESTIE THE OCEAN BELIEVES IN YOU.",
    "I WOULD TRAVEL TO THE SURFACE FOR YOU AND I HATE THE SURFACE.",
    "MY INK RUNS DRY BUT MY LOVE FOR YOU NEVER WILL. THATS CORNY. I DONT CARE.",
    "YOU ARE THE PEARL INSIDE THE WORLDS MOST ANNOYING OYSTER.",
    "IF I COULD WRITE A BOOK ABOUT HOW GREAT YOU ARE ID NEED ALL 8 ARMS TYPING.",
    "YOURE THE ONLY HUMAN I WOULDNT INK ON SIGHT.",
    "I WOULD FIGHT POSEIDON HIMSELF FOR YOU. AND LOSE. BUT ITS THE THOUGHT.",
    "YOU MAKE ME FEEL THINGS IN HEARTS I DIDNT KNOW I HAD. AND I HAVE THREE.",
    "IF SEROTONIN WAS A PERSON IT WOULD LOOK EXACTLY LIKE YOU.",
    "YOURE THE WARM CURRENT IN MY COLD DARK OCEAN.",
    "I DONT SAY THIS TO EVERYONE BUT I WOULD SHARE MY SHRIMP WITH YOU."
  ];

  var ANGRY = [
    "IM NOT MAD IM JUST DISAPPOINTED. AND MAD.",
    "WHO ATE MY SHRIMP. WHO. WAS IT YOU.",
    "I HAVE 8 ARMS AND EVERY ONE OF THEM IS CROSSED RIGHT NOW.",
    "I WILL FLIP THIS TIDE POOL. DONT TEST ME.",
    "MY BLOOD IS BOILING. WHICH IS IMPRESSIVE BECAUSE ITS COLD-BLOODED.",
    "I SWEAR TO POSEIDON IF ONE MORE FISH BUMPS INTO ME.",
    "STOP LOOKING AT ME. STOP IT. I SAID STOP.",
    "EVERYTHING IS FINE. IM FINE. THIS IS FINE. IT IS NOT FINE.",
    "THE AUDACITY OF THIS ENTIRE OCEAN.",
    "DO NOT BOOP MY HEAD. I WILL INK.",
    "IM ONE BAD DAY AWAY FROM BECOMING A LAND OCTOPUS.",
    "MY PATIENCE IS THINNER THAN A JELLYFISH.",
    "I WOKE UP AND CHOSE VIOLENCE. TENTACLE VIOLENCE.",
    "IF LOOKS COULD KILL ID HAVE 3 HEARTS WORTH OF MURDER.",
    "WHOEVER INVENTED MONDAYS DESERVES TO STEP ON A SEA URCHIN.",
    "THE WIFI IS OUT AGAIN. I AM GOING TO SCREAM.",
    "I HAVE THREE HEARTS AND THEY ALL HATE YOU RIGHT NOW.",
    "SOMEBODY MOVED MY ROCK. MY ROCK. MINE.",
    "BREATHE IN. BREATHE OUT. STILL MAD.",
    "THE FACT THAT I CANT SLAM A DOOR MAKES ME ANGRIER.",
    "IM NOT PASSIVE AGGRESSIVE. IM AGGRESSIVE AGGRESSIVE.",
    "I WILL FIGHT EVERY CRAB IN THIS OCEAN. EVERY. ONE.",
    "IM CUTE AND ANGRY AND THATS THE MOST DANGEROUS COMBO.",
    "IM SMALL AND ROUND AND FULL OF RAGE.",
    "I LOOK CUTE BUT I BITE. OCTOPUSES HAVE BEAKS. GOOGLE IT."
  ];

  var CONSPIRATORIAL = [
    "BIRDS ARENT REAL. THEY CHARGE ON POWER LINES.",
    "PIGEONS ARE DRONES. WAKE UP SHEEPLE.",
    "CLOUDS ARE GOVERNMENT PILLOWS.",
    "THE MOON IS JUST THE BACK OF THE SUN.",
    "GRAVITY IS A SUBSCRIPTION SERVICE.",
    "TREES ARE SURVEILLANCE ANTENNAS. LOOK IT UP.",
    "THE ALPHABET IS IN THAT ORDER FOR A DAMN REASON.",
    "DEJA VU IS THE SIMULATION BUFFERING.",
    "FINGERPRINTS ARE JUST SKIN BARCODES THE GOVERNMENT PRE-INSTALLED.",
    "GOOSEBUMPS ARE YOUR BODY TRYING TO GROW FEATHERS BACK.",
    "FIRE TRUCKS ARE ACTUALLY WATER TRUCKS. BIG FIRE DOESNT WANT YOU TO KNOW.",
    "THE DEEP STATE RUNS APPLEBEES.",
    "MATTRESS FIRM IS A MONEY LAUNDERING FRONT.",
    "FINLAND DOESNT EXIST. GOOGLE IT.",
    "5G TURNED MY NEIGHBOR INTO A ROUTER.",
    "DENVER AIRPORT IS AN ILLUMINATI CLUBHOUSE.",
    "BIGFOOT IS REAL AND HES A DAMN GENTLEMAN.",
    "THE ILLUMINATI RUNS COSTCO. FREE SAMPLES ARE MIND CONTROL.",
    "THE PYRAMIDS WERE BUILT BY CATS. EGYPTIANS JUST TOOK CREDIT.",
    "GIRAFFES ARE GOVERNMENT SURVEILLANCE CAMERAS WITH LEGS.",
    "THE MOON LANDING WAS REAL BUT THE MOON IS FAKE.",
    "AUTOCORRECT IS AI SLOWLY REWRITING YOUR THOUGHTS.",
    "DREAMS ARE LEAKED FOOTAGE FROM ALTERNATE DIMENSIONS.",
    "YOUR CAT REPORTS TO SOMEONE. I DONT KNOW WHO BUT SOMEONE.",
    "THE WEATHER CHANNEL CONTROLS THE WEATHER. ITS IN THE NAME."
  ];

  var SAD = [
    "THE OCEAN IS SO BIG AND I AM SO SMALL.",
    "NOBODY EVER ASKS HOW THE OCTOPUS IS DOING.",
    "I HAVE 3 HEARTS AND THEY ALL HURT.",
    "I CHANGED COLOR TO MATCH MY MOOD. ITS BLUE. ALWAYS BLUE.",
    "MY TENTACLES ARE TIRED. MY SOUL IS TIRED.",
    "EVEN THE ABYSS FEELS LONELY SOMETIMES.",
    "I TRIED TO HUG MYSELF BUT MY ARMS GOT TANGLED.",
    "EVERY WAVE TAKES SOMETHING AWAY AND NEVER BRINGS IT BACK.",
    "I INK WHEN IM SCARED BUT LATELY ITS JUST SADNESS INK.",
    "THE DEEP SEA IS QUIET. TOO QUIET.",
    "JELLYFISH DONT HAVE BRAINS. SOMETIMES I ENVY THEM.",
    "I BET NOBODY EVEN NOTICED I CHANGED COLORS.",
    "FISH HAVE FRIENDS. I HAVE EIGHT ARMS AND ZERO FRIENDS.",
    "THE CURRENT KEEPS PUSHING ME PLACES I DONT WANT TO GO.",
    "I COULD DISAPPEAR INTO A TINY CRACK AND NOBODY WOULD LOOK.",
    "THE STARS ARE SO BEAUTIFUL BUT THEYRE ALL ALREADY DEAD.",
    "RAIN IS JUST THE SKY CRYING AND HONESTLY SAME.",
    "SOMETIMES I JUST SIT ON THE OCEAN FLOOR AND THINK.",
    "I MISS THINGS I NEVER HAD.",
    "TODAY FEELS HEAVY. LIKE EXTRA GRAVITY.",
    "ITS OK TO NOT BE OK. THATS WHAT I KEEP TELLING MYSELF.",
    "THE OCEAN HAS NO CEILING BUT IT STILL FEELS LIKE WALLS.",
    "SOMETIMES THE QUIET IS THE LOUDEST THING.",
    "I SAW A HERMIT CRAB FIND A NEW SHELL TODAY. MUST BE NICE.",
    "EVERY BUBBLE I BLOW JUST FLOATS AWAY."
  ];

  var CHAOTIC = [
    "WHAT IF STAIRS GO DOWN AND WE GO UP.",
    "I JUST SNEEZED AND I THINK I SAW GOD.",
    "DOORS ARE JUST POLITE WALLS.",
    "WHAT IF YOUR KNEES BENT THE OTHER WAY.",
    "BANANAS ARE JUST NAKED FRUIT.",
    "MY LEFT TENTACLE DOESNT TRUST MY RIGHT TENTACLE.",
    "TIME IS A FLAT CIRCLE AND IM A ROUND OCTOPUS IN IT.",
    "I FORGOT WHAT I WAS SAYING BUT IM STILL YELLING.",
    "WHAT SOUND DOES A SHADOW MAKE.",
    "IF YOU DIG STRAIGHT DOWN DO YOU END UP IN YESTERDAY.",
    "WHATS INSIDE A MIRROR. MORE MIRROR.",
    "MY BRAIN IS DOING THAT THING AGAIN WHERE IT FORGETS HOW TO BRAIN.",
    "EVERY PIZZA IS A PERSONAL PIZZA IF YOU BELIEVE IN YOURSELF.",
    "I AM GOING TO EAT THE SUN.",
    "IF I SPIN FAST ENOUGH DO I BECOME A BLENDER.",
    "I HAD A THOUGHT BUT IT ESCAPED. ITS LOOSE NOW.",
    "SOMEWHERE A POTATO IS BEING BORN AND NOBODY IS CELEBRATING.",
    "CEILING FANS ARE JUST UPSIDE DOWN HELICOPTERS.",
    "WHAT IF YOUR REFLECTION IS THE REAL YOU AND YOURE THE REFLECTION.",
    "I COUNTED MY ARMS AND GOT A DIFFERENT NUMBER EACH TIME.",
    "ELEVATORS ARE JUST ROOMS THAT KIDNAP YOU VERTICALLY.",
    "IM NOT LOST IM AGGRESSIVELY EXPLORING.",
    "WHAT HAPPENS WHEN AN UNSTOPPABLE FORCE MEETS AN IMMOVABLE OCTOPUS.",
    "THE LETTER W IS LITERALLY DOUBLE U BUT ITS NOT EVEN ROUND.",
    "IF NOTHING STICKS TO TEFLON HOW DO THEY STICK TEFLON TO THE PAN."
  ];

  var HUNGRY = [
    "I COULD EAT AN ENTIRE CORAL REEF RIGHT NOW.",
    "IS THAT FOOD. PLEASE BE FOOD.",
    "MY STOMACH HAS ITS OWN GRAVITATIONAL PULL.",
    "EVERY THOUGHT I HAVE RIGHT NOW IS ABOUT SHRIMP.",
    "IF I DONT EAT IN THE NEXT 5 MINUTES SOMEONE WILL PAY.",
    "FOOD IS NOT A WANT. FOOD IS A NEED. FEED ME.",
    "I HAVE 8 ARMS AND ALL OF THEM WANT SNACKS.",
    "I WOULD SELL 3 OF MY HEARTS FOR A GOOD TACO.",
    "HUNGER MAKES ME PHILOSOPHICAL AND ALSO MEAN.",
    "SNACKS ARE JUST MEALS THAT BELIEVE IN THEMSELVES.",
    "IF YOU EAT FAST ENOUGH THE CALORIES CANT CATCH YOU.",
    "EVERY FOOD IS FINGER FOOD IF YOU HAVE 8 ARMS.",
    "THE OCEAN IS JUST A BUFFET WITH A DRESS CODE.",
    "PIZZA HAS EVERY FOOD GROUP IF YOU TRY HARD ENOUGH.",
    "IM ONE MISSED MEAL AWAY FROM BECOMING A VILLAIN.",
    "NACHOS ARE JUST FANCY CHIP SALAD. FIGHT ME.",
    "MY METABOLISM IS POWERED BY SPITE AND SHRIMP.",
    "I CANT THINK ON AN EMPTY STOMACH AND MY STOMACH IS ALWAYS EMPTY.",
    "A SANDWICH IS JUST A BREAD HUG FOR FOOD.",
    "IM NOT HANGRY. IM JUST HUNGRY AND ALSO ANGRY. WAIT."
  ];

  var TIRED = [
    "I HAVE 3 HEARTS AND THEYRE ALL EXHAUSTED.",
    "MY TENTACLES ARE SO TIRED THEYRE BASICALLY NOODLES.",
    "SLEEP IS JUST A FREE TRIAL OF BEING DEAD AND I WANT THE FULL VERSION.",
    "IM RUNNING ON 1 BRAIN CELL AND ITS ON BREAK.",
    "YAWNING IS MY CARDIO.",
    "EVERY BONE IN MY BODY IS TIRED. I DONT EVEN HAVE BONES.",
    "THE BAGS UNDER MY EYES HAVE THEIR OWN ZIP CODE.",
    "IM NOT LAZY IM IN ENERGY SAVING MODE.",
    "IF NAPPING WAS AN OLYMPIC SPORT ID GET GOLD.",
    "EXISTING IS SO TIRING. WHY DOES CONSCIOUSNESS TAKE SO MUCH EFFORT.",
    "IVE BEEN AWAKE SO LONG I CAN HEAR COLORS.",
    "COFFEE IS JUST BEAN WATER THAT LIES TO YOUR BRAIN.",
    "THE CONCEPT OF MORNING IS VIOLENCE.",
    "MY BRAIN HAS LEFT THE CHAT. MY BODY REMAINS.",
    "I THINK I FELL ASLEEP MIDSENTENCE ONCE AND NOBODY NOTI",
    "PILLOWS ARE JUST FACE MATTRESSES AND I NEED ONE NOW.",
    "IM SO TIRED MY CAMOUFLAGE STOPPED WORKING.",
    "8 ARMS AND NOT ONE OF THEM CAN REACH THE SNOOZE BUTTON.",
    "WHOEVER INVENTED ALARM CLOCKS HAS NEVER KNOWN PEACE.",
    "DO OCTOPUSES DREAM OF ELECTRIC SHRIMP."
  ];

  var SLAPHAPPY = [
    "HAHAHA I DONT EVEN KNOW WHY IM LAUGHING.",
    "EVERYTHING IS FUNNY WHEN YOURE THIS UNHINGED.",
    "I CANT STOP GIGGLING AND ITS BEEN 3 HOURS.",
    "SOMEONE SAID MOIST AND I LOST IT.",
    "IM VIBRATING AT A FREQUENCY ONLY DOGS CAN HEAR.",
    "HAHA WHAT IF CRABS THINK FISH CAN FLY.",
    "I JUST THOUGHT ABOUT PENGUINS AND NOW I CANT BREATHE.",
    "IM SO HAPPY I MIGHT INK.",
    "NOTHING BAD HAS HAPPENED IN 5 MINUTES AND IM SUSPICIOUS.",
    "LIFE IS BEAUTIFUL AND ALSO COMPLETELY INSANE.",
    "I JUST MADE EYE CONTACT WITH A SHRIMP AND WE BOTH LAUGHED.",
    "IM RUNNING ON ZERO SLEEP AND MAXIMUM VIBES.",
    "THE OCEAN SPARKLES AND SO DO I.",
    "MY BRAIN IS DOING THAT THING WHERE IT PLAYS CIRCUS MUSIC.",
    "HAHA WORDS ARE SO WEIRD. WORD. WOOORD. FUNNY.",
    "EVERYTHING TASTES LIKE VICTORY TODAY.",
    "WHY IS THE WORD SPOON SO FUNNY. SPOOOON.",
    "IM LAUGHING SO HARD ALL 3 OF MY HEARTS HURT.",
    "WHAT IF FISH HAVE INSIDE JOKES ABOUT US.",
    "TODAY IS THE BEST DAY EVER AND NOTHING EVEN HAPPENED."
  ];

  var LAZY = [
    "I WOULD DO SOMETHING BUT THAT REQUIRES DOING SOMETHING.",
    "MY BED AND I ARE IN A COMMITTED RELATIONSHIP.",
    "I HAVENT MOVED IN 3 HOURS AND IM AT PEACE WITH THAT.",
    "AMBITION IS A LAND CREATURE PROBLEM.",
    "I WAS GOING TO DO THAT BUT THEN I DIDNT.",
    "MY SPIRIT ANIMAL IS A ROCK. NOT EVEN A COOL ROCK.",
    "PROCRASTINATION IS JUST RESTING BEFORE YOU GET TIRED.",
    "SOMEONE TOLD ME TO SEIZE THE DAY AND I SEIZED A NAP INSTEAD.",
    "I HAVE 8 ARMS AND NONE OF THEM WANT TO DO ANYTHING.",
    "BEING HORIZONTAL IS MY NATURAL STATE.",
    "LAZINESS IS JUST EFFICIENCY WITH BETTER BRANDING.",
    "WHY STAND WHEN YOU CAN SIT. WHY SIT WHEN YOU CAN LIE DOWN.",
    "THE UNIVERSE IS EXPANDING SO TECHNICALLY IM MOVING.",
    "MOTIVATION IS A MYTH INVENTED BY MORNING PEOPLE.",
    "DOING NOTHING IS STILL DOING SOMETHING. CHECKMATE.",
    "EVERY JOURNEY BEGINS WITH A SINGLE STEP AND THATS WHERE MINE ENDS.",
    "IF LAZINESS WAS AN ART FORM ID BE IN A MUSEUM.",
    "I THOUGHT ABOUT EXERCISING AND THAT COUNTS AS A REP.",
    "MY TO-DO LIST HAS ONE ITEM AND ITS IGNORE THE TO-DO LIST.",
    "REST IS NOT A REWARD ITS A WHOLE PERSONALITY."
  ];

  var FAT = [
    "I ATE THE WHOLE THING AND ID DO IT AGAIN.",
    "ROUND IS A SHAPE AND IM NAILING IT.",
    "THE OCEAN IS MY PLATE AND EVERYTHING IN IT IS A SNACK.",
    "I DIDNT GET THIS THICC BY ACCIDENT. THIS TOOK DEDICATION.",
    "MORE CUSHION FOR THE OCEAN PUSHIN.",
    "I HAVE 8 ARMS SO I CAN HOLD 8 SNACKS. EVOLUTION IS BEAUTIFUL.",
    "IM NOT FAT IM JUST EASY TO SEE.",
    "SECOND HELPINGS ARE JUST FIRST HELPINGS THAT BELIEVE IN SEQUELS.",
    "CALORIES DONT COUNT IN INTERNATIONAL WATERS.",
    "IM BUILT FOR COMFORT NOT SPEED AND IM EXTREMELY COMFORTABLE.",
    "THICC THIGHS SAVE LIVES AND I HAVE 8 OF THEM.",
    "I JIGGLE WHEN I MOVE AND ITS CALLED CHARISMA.",
    "BEING AERODYNAMIC IS OVERRATED. I AM SPHERODYNAMIC.",
    "I WENT ON A DIET ONCE. WORST 20 MINUTES OF MY LIFE.",
    "STRETCH MARKS ARE JUST RACING STRIPES FOR SNACKING.",
    "IM NOT OVEREATING IM UNDER-TALL.",
    "MY BLOOD TYPE IS GRAVY.",
    "CURVES ARE JUST STRAIGHT LINES THAT CHOSE HAPPINESS.",
    "I CONTAIN MULTITUDES AND ALSO SEVERAL BURRITOS.",
    "I FLOAT BETTER BECAUSE BUOYANCY LOVES ME."
  ];

  var CHILL = [
    "BRO THE CURRENT WILL TAKE US WHERE WE NEED TO GO.",
    "STRESS IS A LAND CREATURE PROBLEM.",
    "I AM ONE WITH THE WATER AND THE WATER IS VIBING.",
    "EVERYTHING IS TEMPORARY SO WHY WORRY. JUST FLOAT.",
    "THE UNIVERSE DOESNT RUSH AND NEITHER DO I.",
    "IF IT HAPPENS IT HAPPENS. IF NOT THATS COOL TOO.",
    "WORRYING IS LIKE SWIMMING AGAINST THE CURRENT. JUST DONT.",
    "MY VIBE IS UNSHAKEABLE AND MY TENTACLES ARE LOOSE.",
    "NO THOUGHTS JUST CURRENTS.",
    "IM SO RELAXED MY BONELESS BODY IS EVEN MORE BONELESS.",
    "TIME IS AN ILLUSION AND RIGHT NOW IS PERFECT.",
    "DUDE WHAT IF THE OCEAN IS JUST THE SKYS REFLECTION. WAIT.",
    "HAVE YOU EVER REALLY LOOKED AT A CORAL. LIKE REALLY LOOKED.",
    "EVERYTHING IS CONNECTED BRO. EVERYTHING.",
    "NOTHING MATTERS IN THE BEST POSSIBLE WAY.",
    "THE ANSWER TO EVERY QUESTION IS JUST GO WITH THE FLOW.",
    "I COULD GET MAD OR I COULD NOT. I CHOOSE NOT.",
    "MY ENERGY CANNOT BE DISRUPTED. I AM THE OCEAN.",
    "PEACE ISNT FOUND ITS CHOSEN. I CHOOSE IT EVERY DAY.",
    "NAMASTE IN THE WATER FOREVER."
  ];

  var CREEPY = [
    "I HAVE 8 ARMS AND THEY ALL WANT TO HOLD YOU.",
    "IS IT HOT IN HERE OR IS THAT JUST THE HYDROTHERMAL VENT.",
    "MY LOVE IS DEEPER THAN THE MARIANA TRENCH.",
    "ARE YOU A CORAL REEF BECAUSE I WANT TO EXPLORE EVERY INCH OF YOU.",
    "TENTACLES WERE MADE FOR CUDDLING AND I HAVE EIGHT OF THEM.",
    "YOU MUST BE A BIOLUMINESCENT JELLYFISH BECAUSE YOU LIGHT UP MY OCEAN.",
    "CALL ME AN OCTOPUS BECAUSE I CANT KEEP MY ARMS OFF YOU.",
    "MY 3 HEARTS ALL BEAT FOR YOU AND THATS A LOT OF CARDIO.",
    "BABY IM LIKE AN OCTOPUS. FLEXIBLE AND VERY ATTACHED.",
    "IS YOUR NAME WIFI BECAUSE IM FEELING A CONNECTION.",
    "I WOULD CHANGE COLORS FOR YOU AND THATS THE HIGHEST COMPLIMENT.",
    "LETS GET TANGLED UP. I HAVE THE ARMS FOR IT.",
    "MY SUCTION CUPS ARE TINGLING AND THATS EITHER LOVE OR ALLERGIES.",
    "ROSES ARE RED VIOLETS ARE BLUE I HAVE 8 ARMS AND ALL OF THEM WANT YOU.",
    "THE TIDES ARENT THE ONLY THING RISING WHEN YOURE AROUND.",
    "DO YOU BELIEVE IN LOVE AT FIRST SIGHT OR SHOULD I SWIM BY AGAIN.",
    "MY CAMOUFLAGE CANT HIDE HOW I FEEL ABOUT YOU.",
    "IM NOT CLINGY IM JUST AN OCTOPUS AND THIS IS WHAT WE DO.",
    "EVERY ONE OF MY NEURONS IS THINKING ABOUT YOU. THATS A LOT OF NEURONS.",
    "I DONT NEED OXYGEN I NEED YOUR ATTENTION."
  ];

  var EXCITED = [
    "OH MY GOD OH MY GOD OH MY GOD.",
    "I CANT SIT STILL. NONE OF MY 8 ARMS CAN SIT STILL.",
    "EVERYTHING IS HAPPENING AND I LOVE IT.",
    "TODAY IS GOING TO BE THE BEST DAY EVER I CAN FEEL IT.",
    "MY TENTACLES ARE VIBRATING WITH PURE JOY.",
    "THIS IS THE GREATEST MOMENT OF MY LIFE. AGAIN.",
    "IM SO EXCITED I MIGHT INK AND I DONT EVEN CARE.",
    "EVERYTHING IS BEAUTIFUL AND NOTHING CAN STOP ME.",
    "I HAVE SO MUCH ENERGY RIGHT NOW I COULD FIGHT THE MOON.",
    "THE OCEAN IS AMAZING. LIFE IS AMAZING. YOU ARE AMAZING.",
    "I CANT STOP SMILING AND I DONT HAVE LIPS.",
    "SOMEONE TELL ME TO CALM DOWN SO I CAN IGNORE THEM.",
    "AHHHHHHHHHHHH IN A GOOD WAY.",
    "MY 3 HEARTS ARE BEATING SO FAST RIGHT NOW.",
    "EVERY SINGLE THING IS MY FAVORITE THING RIGHT NOW.",
    "I WOKE UP AND CHOSE MAXIMUM ENTHUSIASM.",
    "THE FUTURE IS BRIGHT AND SO AM I. LITERALLY I AM BIOLUMINESCENT.",
    "IS THIS WHAT COFFEE FEELS LIKE BECAUSE I LOVE IT.",
    "I COULD RUN A MARATHON RIGHT NOW. I DONT HAVE LEGS BUT STILL.",
    "THE VIBES ARE IMMACULATE AND I AM ASCENDING."
  ];

  var NOSTALGIC = [
    "REMEMBER WHEN THE OCEAN WAS QUIETER.",
    "I MISS THE OLD REEF. BEFORE THE CONSTRUCTION.",
    "THEY DONT MAKE TIDES LIKE THEY USED TO.",
    "BACK IN MY DAY WE DIDNT HAVE PLASTIC. GOOD TIMES.",
    "I STILL THINK ABOUT THAT ONE PERFECT SUNSET FROM 2019.",
    "THE OLD CURRENT USED TO HIT DIFFERENT.",
    "REMEMBER WHEN WE DIDNT KNOW WHAT STRESS WAS. THAT WAS NICE.",
    "I FOUND AN OLD SHELL TODAY AND IT SMELLED LIKE MEMORIES.",
    "BACK WHEN I WAS A LITTLE LARVA THINGS WERE SIMPLER.",
    "NOBODY APPRECIATES A GOOD TIDE POOL ANYMORE.",
    "THE MOONLIGHT ON THE WATER LOOKED DIFFERENT BACK THEN.",
    "I USED TO KNOW EVERY FISH IN THIS REEF BY NAME.",
    "SOMETIMES I HEAR A CURRENT AND IT SOUNDS LIKE MY CHILDHOOD.",
    "THE OLD KELP FOREST WAS TALLER. OR MAYBE I WAS SHORTER.",
    "THERE WAS THIS ONE ROCK. PERFECTLY SHAPED. I THINK ABOUT IT DAILY.",
    "THE STARS LOOKED CLOSER FROM THE SHALLOW WATER BACK HOME.",
    "MY GRANDMOTHER COULD CHANGE 47 COLORS. THEY DONT MAKE EM LIKE HER.",
    "THE WATER WAS WARMER THEN. OR MAYBE EVERYTHING JUST FELT WARMER.",
    "I HAD A BEST FRIEND WHO WAS A CRAB. WONDER WHERE HE IS NOW.",
    "SOMETIMES A SMELL HITS YOU AND SUDDENLY YOURE 6 MONTHS OLD AGAIN."
  ];

  var HOMESICK = [
    "I MISS MY ROCK. MY SPECIFIC ROCK.",
    "THE DEEP OCEAN SMELLS LIKE HOME AND I CANT GET THERE.",
    "NOBODY MAKES CURRENT LIKE MY MOM USED TO.",
    "I WONDER IF MY TIDE POOL REMEMBERS ME.",
    "HOME IS WHERE THE HEART IS AND MY 3 HEARTS ARE ALL SOMEWHERE ELSE.",
    "THE WATER HERE TASTES DIFFERENT. NOT BAD JUST NOT HOME.",
    "I LEFT A PIECE OF MYSELF IN THAT REEF AND I WANT IT BACK.",
    "DO YOU EVER MISS A PLACE SO MUCH YOUR TENTACLES ACHE.",
    "THE CURRENT USED TO CARRY ME HOME. NOW IT JUST CARRIES ME AWAY.",
    "I DREW A MAP OF HOME IN THE SAND BUT THE TIDE TOOK IT.",
    "THERES A SPECIFIC TEMPERATURE THAT ONLY EXISTS WHERE I GREW UP.",
    "I TRIED TO MAKE MY DEN LOOK LIKE HOME BUT ITS NOT THE SAME.",
    "THE BIOLUMINESCENCE HERE IS WRONG. THE COLOR IS SLIGHTLY OFF.",
    "HOME WASNT PERFECT BUT IT WAS MINE.",
    "I KEEP SWIMMING EAST HOPING ITLL FEEL LIKE HOME EVENTUALLY.",
    "THE MOON LOOKS THE SAME FROM HERE AND THAT HELPS A LITTLE.",
    "I WONDER IF MY OLD HIDING SPOT IS STILL THERE.",
    "I CARRY HOME IN MY MEMORY BECAUSE I CANT CARRY IT IN MY ARMS.",
    "THE OCEAN IS ALL CONNECTED BUT SOMEHOW MY PART FEELS SO FAR.",
    "ONE DAY ILL GO BACK. ONE DAY."
  ];

  // Shuffle helper
  function shuffle(arr) {
    for (var i = arr.length - 1; i > 0; i--) {
      var j = Math.floor(Math.random() * (i + 1));
      var tmp = arr[i]; arr[i] = arr[j]; arr[j] = tmp;
    }
    return arr;
  }

  // ── Build combined quote pool ──
  function buildPool() {
    var pool = [];
    var sources = [
      [SASSY, "sassy"],
      [SUPPORTIVE, "supportive"],
      [ANGRY, "angry"],
      [CONSPIRATORIAL, "conspiratorial"],
      [SAD, "sad"],
      [CHAOTIC, "chaotic"],
      [HUNGRY, "hungry"],
      [TIRED, "tired"],
      [SLAPHAPPY, "slaphappy"],
      [LAZY, "lazy"],
      [FAT, "fat"],
      [CHILL, "chill"],
      [CREEPY, "creepy"],
      [EXCITED, "excited"],
      [NOSTALGIC, "nostalgic"],
      [HOMESICK, "homesick"]
    ];
    sources.forEach(function (pair) {
      shuffle(pair[0].slice()).forEach(function (q) {
        pool.push({ text: q, mode: pair[1] });
      });
    });
    return shuffle(pool);
  }

  // ── Initialize banner ──
  function init() {
    var container = document.getElementById("octopus-banner");
    if (!container) return;

    // Build DOM
    container.innerHTML =
      '<div class="octo-banner-inner">' +
        '<canvas class="octo-banner-canvas" aria-hidden="true"></canvas>' +
        '<div class="octo-banner-text">' +
          '<span class="octo-banner-mode">~ SASSY OCTOPUS ~</span>' +
          '<span class="octo-banner-quote"></span>' +
        '</div>' +
        '<canvas class="octo-banner-canvas octo-banner-canvas-right" aria-hidden="true"></canvas>' +
      '</div>';

    var canvases = container.querySelectorAll(".octo-banner-canvas");
    var modeEl = container.querySelector(".octo-banner-mode");
    var quoteEl = container.querySelector(".octo-banner-quote");

    // Pick scale based on viewport
    var scale = window.innerWidth < 600 ? 1 : 2;
    drawOctopus(canvases[0], scale);
    drawOctopus(canvases[1], scale);
    // Flip the right one
    canvases[1].style.transform = "scaleX(-1)";

    // Quote cycling
    var pool = buildPool();
    var idx = 0;
    var charIdx = 0;
    var current = pool[0];
    var typing = true;
    var pauseFrames = 0;

    function updateMode(mode) {
      var labels = {
        sassy:           "~ SASSY OCTOPUS ~",
        supportive:      "~ SUPPORTIVE OCTOPUS ~",
        angry:           "~ ANGRY OCTOPUS ~",
        conspiratorial:  "~ CONSPIRATORIAL OCTOPUS ~",
        sad:             "~ SAD OCTOPUS ~",
        chaotic:         "~ CHAOTIC OCTOPUS ~",
        hungry:          "~ HUNGRY OCTOPUS ~",
        tired:           "~ TIRED OCTOPUS ~",
        slaphappy:       "~ SLAP HAPPY OCTOPUS ~",
        lazy:            "~ LAZY OCTOPUS ~",
        fat:             "~ FAT OCTOPUS ~",
        chill:           "~ CHILL OCTOPUS ~",
        creepy:           "~ CREEPY OCTOPUS ~",
        excited:         "~ EXCITED OCTOPUS ~",
        nostalgic:       "~ NOSTALGIC OCTOPUS ~",
        homesick:        "~ HOMESICK OCTOPUS ~"
      };
      modeEl.textContent = labels[mode] || labels.sassy;
      modeEl.className = "octo-banner-mode octo-mode-" + mode;
    }

    function tick() {
      if (pauseFrames > 0) {
        pauseFrames--;
        return;
      }

      if (typing) {
        charIdx++;
        quoteEl.textContent = current.text.substring(0, charIdx);
        if (charIdx >= current.text.length) {
          typing = false;
          pauseFrames = 60; // ~3s pause at full quote
        }
      } else {
        // Move to next quote
        idx = (idx + 1) % pool.length;
        if (idx === 0) pool = buildPool(); // reshuffle when exhausted
        current = pool[idx];
        charIdx = 0;
        typing = true;
        updateMode(current.mode);
        quoteEl.textContent = "";
      }
    }

    updateMode(current.mode);
    setInterval(tick, 50);
  }

  // Run on DOM ready
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
