; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; Build all three environments by default, or specify one via CLI
default_envs = PM_PRODUCTION, PM_BETA, OTA_APP

[extra]
baud = 115200

[common]
src_dir = src
platform = espressif32
framework = arduino
upload_protocol = esptool
upload_speed = 460800
upload_resetmethod = no_reset
board_upload.flash_size = 16MB

monitor_speed = ${extra.baud}
monitor_filters = esp32_exception_decoder
build_src_filter =
    +<*> -<test/>
build_flags =   
                -DARDUINO_USB_MODE=1
                -DARDUINO_USB_CDC_ON_BOOT=1
                -DARDUINO_RUNNING_CORE=1
                -DARDUINO_EVENT_RUNNING_CORE=1
                -DCORE_DEBUG_LEVEL=3
                -I include                          ; Lets files in lib/ see globals.h

lib_deps = 
    adafruit/Adafruit GFX Library@^1.12.0
    adafruit/Adafruit TCA8418@^1.0.2
    adafruit/RTClib@^2.1.4
    olikraus/U8g2@^2.36.4
    adafruit/Adafruit MPR121@^1.1.3
    gmarty2000/Buzzer@^1.0.0
    tobozo/ESP32-targz
    fastled/FastLED
    https://github.com/esp32beans/ESP32_USB_Host_HID.git
    https://github.com/jingoro2112/wrench.git
    https://github.com/ashtf8/GxEPD2_Editable_useFastFullUpdate


; --- PocketMage Production Model (N16R2 - Quad PSRAM Enabled) ---
[env:PM_PRODUCTION]
extends = common
board = esp32-s3-devkitc-1
build_flags = 
    ${common.build_flags} 
    '-DOS_VERSION_STR="V1.8.0"'    ; Software version number
    -DOTA_APP_FLAG=0
    -DPOCKETMAGE_HW_VERSION=2   ; 2 = Production
    -DBOARD_HAS_PSRAM=1         ; Production has Quad PSRAM
board_build.arduino.memory_type = qio_qspi
board_build.partitions = partitions_4APP.csv

; --- PocketMage Beta (N16R8 - PSRAM Forced Disabled) ---
[env:PM_BETA]
extends = common
board = esp32-s3-devkitc-1                 
build_flags = 
    ${common.build_flags} 
    '-DOS_VERSION_STR="BETA V1.8.0"'    ; Software version number
    -DOTA_APP_FLAG=0
    -DPOCKETMAGE_HW_VERSION=1   ; 1 = Beta
    -DBOARD_HAS_PSRAM=0         ; Beta has no PSRAM
board_build.partitions = partitions_4APP.csv

; --- UNIVERSAL OTA APP (Hardware Agnostic) ---
[env:OTA_APP]
extends = common
board = esp32-s3-devkitc-1
build_flags= 
    ${common.build_flags} 
    -DOTA_APP_FLAG=1
    -DPOCKETMAGE_HW_VERSION=0   ; 0 = Universal
    -DBOARD_HAS_PSRAM=0         ; No PSRAM for compatibility
board_build.partitions = partitions_OTA_APP.csv