services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./hello-world:/project
    working_dir: /project

  build-img-receiver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./img-receiver:/project
    working_dir: /project

  build-sassy-octopus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./sassy-octopus:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-supportive-octopus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./supportive-octopus:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-angry-octopus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./angry-octopus:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-conspiratorial-octopus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conspiratorial-octopus:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-sad-octopus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./sad-octopus:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-chaotic-octopus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./chaotic-octopus:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-hungry-octopus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./hungry-octopus:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-tired-octopus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tired-octopus:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-slaphappy-octopus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./slaphappy-octopus:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-lazy-octopus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./lazy-octopus:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-fat-octopus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./fat-octopus:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-chill-octopus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./chill-octopus:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-creepy-octopus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./creepy-octopus:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-excited-octopus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./excited-octopus:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-nostalgic-octopus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nostalgic-octopus:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-homesick-octopus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./homesick-octopus:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-mood-selector:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./mood-selector:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-joystick-mood-selector:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./joystick-mood-selector:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-moodselector-sound:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./moodselector-sound:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-moodselector-sound-wifi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./moodselector-sound-wifi:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project

  build-dilder-hub:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dilder-hub:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project
