services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./hello-world:/project
    working_dir: /project

  build-img-receiver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./img-receiver:/project
    working_dir: /project

  build-sassy-octopus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./sassy-octopus:/project
      - ./hello-world/lib:/project/lib
    working_dir: /project
